builds:
  - env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X k8s.io/component-base/version/verflag.programName={{ .ProjectName }}
      - -X k8s.io/component-base/version.buildDate={{ .CommitDate }}
      - -X k8s.io/component-base/version.gitCommit={{ .FullCommit }}
      - -X k8s.io/component-base/version.gitMajor={{ .Major }}
      - -X k8s.io/component-base/version.gitMinor={{ .Minor }}
      - -X k8s.io/component-base/version.gitTreeState={{ .Env.GIT_TREE_STATE }}
      - -X k8s.io/component-base/version.gitVersion=v{{ trimprefix .Version "v" }}
    goos:
      - linux
      - darwin
      - freebsd
      - windows
    goarch:
      - amd64
      - '386'
      - arm
      - arm64
    binary: '{{ .ProjectName }}'

archives:
  - format: tar.gz
    rlcp: true
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- if eq .Os "darwin" }}Darwin
      {{- else if eq .Os "linux" }}Linux
      {{- else }}{{ .Os }}{{ end }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    files:
      - plugin.yaml
      - LICENSE
      - completion.yaml
      - install-binary.sh

snapshot:
  name_template: "{{ incminor .Tag }}-dev"

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256

# signs:
#   - artifacts: checksum
#     args:
#       - "--batch"
#       - "--local-user"
#       - "{{ .Env.GPG_FINGERPRINT }}" # set this environment variable for your signing key
#       - "--output"
#       - "${signature}"
#       - "--detach-sign"
#       - "${artifact}"

changelog:
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
