builds:
  - env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X github.com/d2iq-labs/helm-list-images/version.Version={{.Version}}
      - -X github.com/d2iq-labs/helm-list-images/version.BuildDate={{.Date}}
      - -X github.com/d2iq-labs/helm-list-images/version.Revision={{.Commit}}
      - -X github.com/d2iq-labs/helm-list-images/version.Platform={{ .Runtime.Goos }}/{{ .Runtime.Goarch }}
    goos:
      - linux
      - darwin
      - freebsd
      - windows
    goarch:
      - amd64
      - '386'
      - arm
      - arm64
    binary: '{{ .ProjectName }}'

archives:
  - format: tar.gz
    rlcp: true
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- if eq .Os "darwin" }}Darwin
      {{- else if eq .Os "linux" }}Linux
      {{- else }}{{ .Os }}{{ end }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    files:
      - plugin.yaml
      - LICENSE
      - completion.yaml
      - install-binary.sh

snapshot:
  name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Runtime.Goos }}_{{ .Runtime.Goarch }}"

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256

# signs:
#   - artifacts: checksum
#     args:
#       - "--batch"
#       - "--local-user"
#       - "{{ .Env.GPG_FINGERPRINT }}" # set this environment variable for your signing key
#       - "--output"
#       - "${signature}"
#       - "--detach-sign"
#       - "${artifact}"

changelog:
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
