# Copyright 2021-2023 D2iQ, Inc. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

repos:
- repo: https://github.com/tekwizely/pre-commit-golang
  rev: v1.0.0-rc.1
  hooks:
  - id: go-mod-tidy
    stages: [commit]
  - id: golangci-lint-mod
    stages: [commit]
    args: ["--fix"]
- repo: local
  hooks:
  -   id: go-generate
      name: go-generate
      entry: make go-generate
      language: system
      types: [go]
      pass_filenames: false
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: trailing-whitespace
    stages: [commit]
  - id: check-yaml
    args: ["-m", "--unsafe"]
    stages: [commit]
    exclude: ^example/chart/
  - id: mixed-line-ending
    args: ["-f", "lf"]
    exclude: \.bat$
    stages: [commit]
  - id: no-commit-to-branch
    stages: [commit]
  - id: check-added-large-files
    stages: [commit]
  - id: check-case-conflict
    stages: [commit]
  - id: check-merge-conflict
    stages: [commit]
  - id: check-executables-have-shebangs
    stages: [commit]
  - id: check-symlinks
    stages: [commit]
  - id: end-of-file-fixer
    stages: [commit]
    exclude: ^docs/doc/
- repo: https://github.com/jorisroovers/gitlint
  rev: v0.19.1
  hooks:
  - id: gitlint
    stages: [commit-msg]
- repo: https://github.com/jumanjihouse/pre-commit-hooks
  rev: 3.0.0
  hooks:
  - id: shfmt
    stages: [commit]
    args: ["-s", "-i", "2"]
  - id: script-must-have-extension
    stages: [commit]
- repo: https://github.com/shellcheck-py/shellcheck-py
  rev: v0.9.0.5
  hooks:
  - id: shellcheck
    stages: [commit]
    args: ["-e", "SC2211"]
