# Copyright 2021-2023 D2iQ, Inc. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

name: build-on-macos

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main

jobs:
  build-and-run:
    runs-on: macos-13
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up devenv.sh environment
        uses: d2iq-labs/devenv.sh-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: make build-snapshot

      - name: Run binary
        run: |
          ./dist/helm-list-images_darwin_amd64_v1/helm-list-images -h
